apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-inference-autoprov 
spec:
  nodePoolAutoCreation:
    enabled: true
  priorities:
  - gpu:
      type: nvidia-tesla-a100
      count: 1