apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: inference # Replace with the actual namespace
  name: job-can-get-deployment-status
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-can-get-deployment-status-binding
  namespace: inference # Replace with the actual namespace
subjects:
  - kind: ServiceAccount
    name: default # Replace with the actual ServiceAccount name if not using default
    namespace: inference # Replace with the actual namespace
roleRef:
  kind: Role
  name: job-can-get-deployment-status
  apiGroup: rbac.authorization.k8s.io